"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const student_controller_1 = require("../controllers/student.controller");
const router = (0, express_1.Router)();
router.post('/login', student_controller_1.loginStudent);
router.get('/', student_controller_1.getAllStudents);
router.post('/', student_controller_1.createStudent);
router.put('/:id', student_controller_1.updateStudent);
router.delete('/:id', student_controller_1.deleteStudent);
exports.default = router;
